### ISSUE TITLE
error in 'query_exec'

### ISSUE THREAD

**Issue by wisekh6** [isb-cgc/examples-R#33]
Hello,

I tried to run the following commands, but it failed

`
project  <-"isb-cgc-test-173402"
theTable <- "isb-cgc:tcga_201510_alpha.Clinical_data"

querySql <- paste("SELECT COUNT(1) FROM [", theTable, "]", sep="")
querySql

result <- query_exec(querySql, project=project)
result

Auto-refreshing stale OAuth token.
Error: Access Denied: Table isb-cgc:tcga_201510_alpha.Clinical_data: The user wisekh6@gmail.com does not have permission to query table isb-cgc:tcga_201510_alpha.Clinical_data.
`
I believe 'isb-cgc:tcga_201510_alpha.Clinical_data' will be publicly available, and therefore, I would have permission to access. But, I might be wrong.

I wonder if you can let me know how to avoid this error.

Best,

**Comment by smrgit** [comment]
The ``isb-cgc:tcga_201510_alpha`` BigQuery dataset is no longer public as it is out of date -- the direct replacement dataset is ``isb-cgc:tcga_201607_beta``.  Since then, however, we started changing some terminology (eg from "Participant" to "case") in order to align more closely with the Genomic Data Commons (NCI-GDC), and the newest dataset is ``isb-cgc:TCGA_bioclin_v0``.  We recommend that you use the most recent BigQuery tables as described in our documentation [here](http://isb-cancer-genomics-cloud.readthedocs.io/en/latest/sections/data/data2/data_in_BQ.html) -- although note that field names have changed.

**Comment by wisekh6** [comment]
Got it.
Thank you so much for your quick response.

**Comment by smrgit** [comment]
Of course -- if you have any comments or other questions about the ISB-CGC tables in BigQuery or any of the other ISB-CGC resources (documentation [here](http://isb-cancer-genomics-cloud.readthedocs.io/en/latest/index.html)), please let us know.  If you haven't already seen it, please take a look at our "Query of the Month" page [here](http://isb-cancer-genomics-cloud.readthedocs.io/en/latest/sections/QueryOfTheMonthClub.html) -- it has some great examples showing the power of BigQuery and how to combine that with the power of R.
